language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - "pip install -q -e ."
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=pygazebo setup.py test"
after_success:
    coveralls
